[package]
name = "artbounty"

[package.metadata.leptos]
name = "artbounty"
bin-package = "artbounty-backend"
lib-package = "artbounty-frontend"
output-name = "artbounty_1"
site-root = "target/site"
site-pkg-dir = "pkg"
tailwind-input-file = "style/tailwind.css"
assets-dir = "assets"
# site-addr = "127.0.0.1:3000"
# site-addr = "[fe80::6b0b:bdc1:8191:2bad]:3000"
# site-addr = "[::1]:3000"
site-addr = "0.0.0.0:3000"
# site-addr = "192.168.0.164:3000"
reload-port = 3001
end2end-cmd = "yarn playwright test"
end2end-dir = "e2e"
browserquery = "defaults"
watch = true
env = "DEV"
lib-profile-release = "wasm-release"
bin-features = []
lib-features = ["hydrate"]
bin-default-features = false
lib-default-features = false
